# Generated by Django 4.2.14 on 2024-07-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('carpeta', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento_padre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('carpeta', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='firmas_views.documento')),
            ],
        ),
    ]
