# Generated by Django 4.2.14 on 2024-07-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmas_views', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='documento',
        ),
    ]
