# Generated by Django 4.2.14 on 2024-07-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas_views', '0002_rename_nombre_documento_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoversion',
            name='documento_padre',
        ),
        migrations.AddField(
            model_name='documentoversion',
            name='documento_padre_id',
            field=models.IntegerField(null=True),
        ),
    ]
