# Generated by Django 4.2.14 on 2024-07-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmas_views', '0003_remove_documentoversion_documento_padre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoversion',
            old_name='documento_padre_id',
            new_name='documento_padre',
        ),
    ]
